### ISSUE TITLE
first mistake

### ISSUE THREAD

**Issue by earth145** [SlumberDemon/Surfer#3]
Unable to search in deta space, you can display the page, but when searching in the search engine, it displays an error

**Comment by SlumberDemon** [comment]
Could you please share the error message and some screenshots? Also what do you mean with `first mistake` title?

**Comment by SlumberDemon** [comment]
I found the issue, working on a fix now! Thanks for reporting, a patch will be ready to install asap!

**Comment by SlumberDemon** [comment]
Fixes are now avalible! Update to the latest version to get them!
